### ISSUE TITLE
redux store.subscribe is firing repeatedly once I use log monitor.

### ISSUE THREAD

**Issue by aintnorest** [gaearon/redux-devtools-log-monitor#12]
I have a redux store.subscribe that fires the function its past about once a second once I start using the LogMonitor. The project is very tiny with one reducer with 3 actions and only 3 components. I can console all the actions and know I'm not spamming it. Is this normal behavior? It's totally possible I'm blaming the wrong library but this seems to be the point at which the problem is starting.

**Comment by gaearon** [comment]
This is normal. Is it causing any problems?

**Comment by aintnorest** [comment]
It seems under performant and I don’t completely understand why the log monitor needs this to function. As I only use the monitor in development and not production it’s not a deal breaker. In truth I just wanted to make sure I wasn’t doing something to cause it unnecessarily. I tried asking in #redux reactiflux discord channel but only received that it must be something I was doing. Thanks for the response.

**Comment by gaearon** [comment]
Can you clarify what you mean by "seems underperformant"? Are you seeing a specific performance issues caused by this, or are you making a guess?

**Comment by tony-kerz** [comment]
i just ran into this as well.

i have a store subscriber, and i put a log message in it, and when i saw it being fired once a second,
i thought i botched something.

eventually, i placed a log message in `store.dispatch()` and realized that in addition to my subscriber, there were an additional 3 subscribers from various libraries (not sure exactly which), so these 4 listeners were being called every second due to the `UPDATE_SCROLL_TOP` action.

i suppose it is probably a negligible performance hit, but i have to admit that my ocd would prefer to be able to skirt those extra calls if the dock-monitor is hidden (which mine typically is).

**Comment by zalmoxisus** [comment]
Actually, guys, it's easy to fix. Just remove the setInterval and use React's `onScroll` event. So, if it bothers anyone, feel free to contribute :)

**Comment by zalmoxisus** [comment]
Another issue here is that since we get new props as `{ ... monitorState: { initialScrollTop: ... } }`, rect-pure-render doesn't help (`shallowEqual` cannot compare it) and we have the monitor rerendered every second, which is a huge issue (@aintnorest, I'd suggest to reopen it).

Of course we could find a solution to replace `setInterval` with React's `onScroll` event (not sure whether it works for a html element or only for the window), but even in this case it wouldn't be a good point to rerender the component on every scroll.

**Comment by gaearon** [comment]
Can you please clarify again what is the issue with re-rendering once a second? Are you having a performance issue, or is it a guess that it might be an issue?

**Comment by zalmoxisus** [comment]
@gaearon, sorry it was just a guess and I didn't provide any details, I just noticed that `react-pure-render` is useless here.

Just to reassure, I dispatched a thousands of actions, then having the app idle without any actions, it is taking about 30% of CPU, where more than 80% are from `updateScrollTop -> dispatch -> ReactComponent.setState`, even when the monitor is hidden. When it is not idle, even without dispatching any actions, the app runs to 100% of CPU.

Probably it is just an extreme case and we could just dispatch the `COMMIT` (or setting the `autocommit` we introduced in the extension).

**Comment by chrisnojima** [comment]
Hi, I ran into this problem as well. I was trying to debug why my component was updating (due to the store being updated since this action fires). It might be nice if the flag to control this was inspected to decide if the timer should fire or not (vs it just ignoring it in the reducer)

**Comment by zalmoxisus** [comment]
@chrisnojima, we have such flag, just set `preserveScrollTop` to `false`. As indicated [here](https://github.com/gaearon/redux-devtools-log-monitor#props).

I'd suggest to have the `false` value by default to avoid confusion. When setting this to `true`, one should expect some performance issues.

**Comment by chrisnojima** [comment]
The issue is that flag is only acted on by the reducer. I'm using the dockMonitor with the LogMonitor inside of it (like all the examples) The timer is determined by mount/dismount but the dockMonitor (even when hidden) never unmounts since it just makes its dimensions 0. So if i have preserveScrollTop = false and even the entire thing hidden , it still fires the event every second

**Comment by zalmoxisus** [comment]
Did you use it like that?

```js
const DevTools = createDevTools(
  <DockMonitor toggleVisibilityKey='ctrl-h'
               changePositionKey='ctrl-q'>
    <LogMonitor theme='tomorrow' preserveScrollTop={false} />
  </DockMonitor>
);
```

**Comment by chrisnojima** [comment]
I'm actually also using the hiding flag
```
export default createDevTools(
  <DockMonitor
    toggleVisibilityKey='ctrl-h'
    changePositionKey='ctrl-q'
    defaultIsVisible={false}>
    <LogMonitor theme='tomorrow' select={reduxDevToolsSelect} preserveScrollTop={false}/>
  </DockMonitor>)
```

Even with this setup it'll fire the action every second. You'll see no dock monitor, but its visibility is just off, its still mounted / in the dom

**Comment by gaearon** [comment]
In v1.0.2, specifying `preserveScrollTop={false}` will make sure actions are not fired.
